### ISSUE TITLE
[BUG] "Error setting up entry for {email} for hive" after 2022.7.1 upgrade

### ISSUE THREAD

**Issue by TomBeech85** [Pyhass/Hive-Custom-Component#119]
**Describe the bug**
Since upgrading to 2022.7.1, the hive integration no longer loads correctly. The logs state that there was an error setting up an entry for my email. (see screenshot)

**To Reproduce**
Steps to reproduce the behaviour:

1. In a 2022.6.x build of HA, setup a working Hive integration
2. Upgrade to 2022.7.x
3. Observe the failure

**Expected behaviour**

**Screenshots**
<img width="653" alt="image" src="https://user-images.githubusercontent.com/85169303/177984815-d1038fd1-d64a-4f3a-9a7d-16a9d8fc25fc.png">

**Comment by KJonline** [comment]
This should be fixed in the new release

**Comment by StuartHaire** [comment]
Hi @KJonline I'm still getting this same issue. Updated HA to 2022.7.5 and updating hive to the latest version;
![hive-error](https://user-images.githubusercontent.com/38922184/179725733-331a8a79-9d00-42a8-8581-074255562c7d.JPG)
